### PR TITLE
:sparkles: Drug registration

### PR DESCRIPTION
**Pull request by OakenKnight**

### CODE REVIEW

**Comment by jelena-vlajkov** [comment]
I recommend using mappers with dto objects, because they should not contain any kind of logic. 
Also you can use Java stream to avoid long for loops and make code seem more clean.
[Link to Java stream tutorial](https://winterbe.com/posts/2014/07/31/java8-stream-tutorial-examples/)

**Comment by st3fan7** [comment]
That what she said

**Comment by jelena-vlajkov** [comment]
Anyways, good job, mate! 👍 ❤️

**Comment by st3fan7** [comment]
Good job! 👌

**Pull request merged**
